title = "Ploder"
gitRepoUrl = "https://github.com/denispionicul/Ploder" # From Git

gitSourceBranch = "main"

[home]
enabled = true
includeReadme = false # Optional

[docusaurus]
tagline = "Custom Explosions made easy."