gitSourceBranch = "main"

[home]
enabled = true
includeReadme = false # Optional

[docusaurus]
organizationName = "denispionicul"
projectName = "Ploder"
url = "https://denispionicul.github.io"
baseUrl = "/Ploder"
tagline = "Custom Explosions made easy."