[package]
name = "denispionicul/ploder"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Custom explosions with very customisable settings and features."

[dependencies]
Signal = "sleitnick/signal@1.5.0"
Trove = "sleitnick/trove@1.0.1"